services:
  # labzap:
  #   extends:
  #     file: docker-compose-onprimise.yml
  #     service: labzap

  # polling:
  #   extends:
  #     file: docker-compose-onprimise.yml
  #     service: polling

  database:
    image: postgres:16.0-alpine
    env_file:
      - .env
    volumes:
      - ./DB:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
      # - labzap
