services:
  whatsapp-http-api:
    image: devlikeapro/whatsapp-http-api
    container_name: whatsapp-http-api
    ports:
      - "3000:3000/tcp"
    environment:
      # Environment variables from https://waha.devlike.pro/docs/how-to/config/
      - WHATSAPP_HOOK_URL=https://httpbin.org/post # Verificar URL do projeto em PRD
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    restart: always

  database:
    image: postgres:16.0-alpine
    env_file:
      - .env
    volumes:
      - ./DB:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
      - whatsapp-http-api
