# Generated by Django 5.0.4 on 2024-04-24 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_schedule_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecalendarintegration',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.schedule'),
        ),
        migrations.AlterField(
            model_name='schedulewhatsappintegration',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.schedule'),
        ),
    ]
