# Generated by Django 5.0.4 on 2024-04-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_schedulecalendarintegration_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedcalendar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharedcalendar',
            name='sector',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
