# Generated by Django 5.0.4 on 2024-04-25 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sharedcalendar_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='shared_calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.sharedcalendar'),
        ),
    ]
