# Generated by Django 5.0.4 on 2024-05-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_schedule_calendar_event_id_schedule_day_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecalendarintegration',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Calendar Event Data'),
        ),
    ]
