# Generated by Django 5.0.4 on 2024-05-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_schedulecalendarintegration_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecalendarintegration',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_integration', to='core.schedule'),
        ),
        migrations.AlterField(
            model_name='schedulewhatsappintegration',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_integration', to='core.schedule'),
        ),
        migrations.DeleteModel(
            name='ScheduleHistory',
        ),
    ]
