# Generated by Django 5.0.4 on 2024-09-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_schedule_has_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedcalendar',
            name='laboratory_phone_number',
            field=models.CharField(default='no-phone', max_length=128),
            preserve_default=False,
        ),
    ]
